### PR TITLE
Fix: woocommerce outdated template

### LINKED ISSUE #22: (dokani) contains outdated copies of some WooCommerce template files
dokani-develop/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 4.0.0,

### PR DESCRIPTION
**Pull request by ahsanshaheen199**
WooCommerce outdated template issue has been fixed. It fixes #22

### CODE REVIEW

File: woocommerce/cart/mini-cart.php [hunk 1]
```diff
@@ -13,75 +13,73 @@
...
 
-if ( ! defined( 'ABSPATH' ) ) {
-    exit; // Exit if accessed directly
-}
+defined( 'ABSPATH' ) || exit;
 
-?>
-
-<?php do_action( 'woocommerce_before_mini_cart' ); ?>
+do_action( 'woocommerce_before_mini_cart' ); ?>
```
Comment (shohag121) [inline woocommerce/cart/mini-cart.php:22]: Kindly do the same for the below PHP blocks.

**Review by shohag121 — CHANGES_REQUESTED** [review]

**Review by shohag121 — APPROVED** [review]
